services:
    noara.admin.form.races:
        class: AdminBundle\Service\Form\RacesForm
        lazy: true
        shared: true
        arguments:
            - "@form.factory"

    noara.admin.persistance.races:
      class: AdminBundle\Service\Persistance\RacesPersistance
      lazy: true
      shared: true
      arguments:
          - "@doctrine.orm.entity_manager"

    noara.admin.dao.races:
      class: AdminBundle\Service\DAO\RacesDao
      lazy: true
      shared: true
      arguments:
          - "@doctrine.orm.entity_manager"

    noara.admin.dao.post:
      class: AdminBundle\Service\DAO\PostDao
      lazy: true
      shared: true
      arguments:
          - "@doctrine.orm.entity_manager"

    noara.admin.form.post:
      class: AdminBundle\Service\Form\PostForm
      lazy: true
      shared: true
      arguments:
          - "@form.factory"

    noara.admin.persistance.post:
      class: AdminBundle\Service\Persistance\PostPersistance
      lazy: true
      shared: true
      arguments:
          - "@doctrine.orm.entity_manager"

    noara.admin.dao.characters:
      class: AdminBundle\Service\DAO\CharactersDao
      lazy: true
      shared: true
      arguments:
          - "@doctrine.orm.entity_manager"

    noara.admin.form.characters:
            class: AdminBundle\Service\Form\CharactersForm
            lazy: true
            shared: true
            arguments:
                - "@form.factory"

    noara.admin.persistance.characters:
          class: AdminBundle\Service\Persistance\CharactersPersistance
          lazy: true
          shared: true
          arguments:
              - "@doctrine.orm.entity_manager"

    noara.admin.utils.activator:
          class: AdminBundle\Service\Utils\ActivatorUtils
          lazy:
          shared: true
          arguments:
              - "@noara.admin.dao.post"
              - "@noara.admin.dao.races"
              - "@noara.admin.dao.characters"
              - "@noara.admin.persistance.post"
              - "@noara.admin.persistance.races"
              - "@noara.admin.persistance.characters"