admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   admin/

page:
    resource: "@PageBundle/Controller/"
    type:     annotation
    prefix:   noara/

app:
    resource: '@AppBundle/Controller/'
    type: annotation
