<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function getAllPost()
    {
        //Création du query Builder
        $qb = $this->createQueryBuilder("post");

        $qb
            ->select("post")
        ;
        return $qb->getQuery();
    }
}
