<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * class RacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RacesRepository extends EntityRepository
{
    /**
     * @return Query
     */
    public function getAllRaces()
    {
        //Création du queryBuilder
        $qb = $this->createQueryBuilder("races");

        //Récupération des personnages lié à la race
        $qb
            ->addSelect("characters")
            ->leftJoin("races.characters", "characters")
        ;

        //Renvoi uniquement la requete
        return $qb->getQuery();
    }
}
