services:
    noara.admin.form.races:
        class: AdminBundle\Service\Form\RacesForm
        lazy: true
        shared: true
        arguments:
            - "@form.factory"

    noara.admin.persistance.races:
      class: PageBundle\Service\Persistance\RacesPersistance
      lazy: true
      shared: true
      arguments:
          - "@doctrine.orm.entity_manager"

    noara.dao.races:
      class: AdminBundle\Service\DAO\RacesDao
      lazy: true
      shared: true
      arguments:
          - "@doctrine.orm.entity_manager"

    noara.dao.posts:
      class: AdminBundle\Service\DAO\PostDao
      lazy: true
      shared: true
      arguments:
          - "@doctrine.orm.entity_manager"

    noara.dao.characters:
          class: AdminBundle\Service\DAO\CharactersDao
          lazy: true
          shared: true
          arguments:
              - "@doctrine.orm.entity_manager"